---
- name: Create some files
  hosts: jenkins
  gather_facts: no
  # vars_files:
  #   - vars.yml
  remote_user: "{{ remote_user }}"
  tasks:
  
    - name: Get user ID
      shell: id
      register: user_id

    - debug: var=user_id.stdout_lines

    - name: Create file /home/user1/ansible.yml
      file:
        path: /home/user1/ansible.yml
        state: touch
      #remote_user: user1
      # become: true
      # become_method: su
      # become_user: user1
    
      
    - name: Get user ID - remote user
      shell: id
      register: user_id
      remote_user: "{{ remote_user }}"

    - debug: var=user_id.stdout_lines

    - debug: var=ansible_user
    - debug: var=remote_user

    - name: Create file /home/admin2/ansible.yml
      file:
        path: /home/admin2/ansible.yml
        state: touch
      remote_user: "{{ remote_user }}"
      # become: true
      # become_method: su
      # become_user: admin1
      # vars:
      #   ansible_become_password: "{{ sudo_password }}"


    # - name: Create file /etc/some_file.yml
    #   file:
    #     path: /etc/some_file.yml
    #     state: touch
      #become_user: admin1
