---
- name: Test playbook
  hosts: all
  gather_facts: no
  tasks:
  
    - name: Write message
      debug:
        msg: Hello World!
        
    - name: Append a line to /etc/hosts
      command: echo test >> /etc/hosts
      
    - name: whoami
      command: ifconfig
      register: whoami
      
    - debug: var=whoami
    
