---
- name: Test playbook
  hosts: jenkins
  gather_facts: no
  tasks:
  
    - name: show user id
      shell: id
        
    - name: whoami
      command: whoami
      register: whoami
      
    - debug: var=whoami
    
    - debug: var=become_user
        
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/some_directory_1
        state: present
      #become: true
      #become_user: sudouser
      #become_password: Welcome123
        #mode: '0755'
    
